# Funding options for the project
# You can add your sponsor links here when ready

# github: [your-username]
# ko_fi: your-kofi-username
# patreon: your-patreon-username
# custom: ["https://your-website.com/donate"]
